package entity;

import java.util.ArrayList;
import java.util.Date;

public class Report {

    private String reportType;
    private Date reportDate;

   
    private Date startDate;
    private Date endDate;
    private String generatedBy;
    private String exportFormat;

    public Report(String reportType, Date reportDate) {
        this.reportType = reportType;
        this.reportDate = reportDate;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public Date getReportDate() {
        return reportDate;
    }

    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public String getExportFormat() {
        return exportFormat;
    }

    public void setExportFormat(String exportFormat) {
        this.exportFormat = exportFormat;
    }

    
    public void salesReport(ArrayList<SalesTransaction> transactions) {

        double revenue = 0;

        for (SalesTransaction st : transactions) {
            revenue += st.getTotalAmount();
        }

        System.out.println("\n========== SALES REPORT ==========");
        System.out.println("Report Type   : " + reportType);
        System.out.println("Report Date   : " + reportDate);

        if (startDate != null) {
            System.out.println("Start Date    : " + startDate);
        }

        if (endDate != null) {
            System.out.println("End Date      : " + endDate);
        }

        if (generatedBy != null) {
            System.out.println("Generated By  : " + generatedBy);
        }

        if (exportFormat != null) {
            System.out.println("Export Format : " + exportFormat);
        }

        System.out.println("Total Orders  : " + transactions.size());
        System.out.println("Total Revenue : " + revenue + " VND");
    }

  
    public void bestSellingProducts(ArrayList<SalesTransaction> transactions) {

        String[] productNames = new String[100];
        int[] quantities = new int[100];
        int count = 0;

        for (SalesTransaction st : transactions) {

            ArrayList<OderDetail> details = st.getOrderDetails();

            for (OderDetail od : details) {

                String name = od.getProduct().getName();
                boolean found = false;

                for (int i = 0; i < count; i++) {

                    if (productNames[i].equalsIgnoreCase(name)) {
                        quantities[i] += od.getQuantity();
                        found = true;
                        break;
                    }
                }

                if (!found) {
                    productNames[count] = name;
                    quantities[count] = od.getQuantity();
                    count++;
                }
            }
        }

        
        for (int i = 0; i < count - 1; i++) {
            for (int j = i + 1; j < count; j++) {

                if (quantities[j] > quantities[i]) {

                    int tempQuantity = quantities[i];
                    quantities[i] = quantities[j];
                    quantities[j] = tempQuantity;

                    String tempName = productNames[i];
                    productNames[i] = productNames[j];
                    productNames[j] = tempName;
                }
            }
        }

        System.out.println("\n===== BEST-SELLING PRODUCTS =====");

        for (int i = 0; i < count; i++) {
            System.out.println(
                    (i + 1) + ". "
                    + productNames[i]
                    + " - "
                    + quantities[i]
                    + " units");
        }
    }

    
    public void highestPurchaseCustomer(ArrayList<SalesTransaction> transactions) {

        String[] customerNames = new String[100];
        double[] totalMoney = new double[100];
        int count = 0;

        for (SalesTransaction st : transactions) {

            String name = st.getCustomer().getName();
            boolean found = false;

            for (int i = 0; i < count; i++) {

                if (customerNames[i].equalsIgnoreCase(name)) {
                    totalMoney[i] += st.getTotalAmount();
                    found = true;
                    break;
                }
            }

            if (!found) {
                customerNames[count] = name;
                totalMoney[count] = st.getTotalAmount();
                count++;
            }
        }

      
        for (int i = 0; i < count - 1; i++) {
            for (int j = i + 1; j < count; j++) {

                if (totalMoney[j] > totalMoney[i]) {

                    double tempMoney = totalMoney[i];
                    totalMoney[i] = totalMoney[j];
                    totalMoney[j] = tempMoney;

                    String tempName = customerNames[i];
                    customerNames[i] = customerNames[j];
                    customerNames[j] = tempName;
                }
            }
        }

        System.out.println("\n===== CUSTOMERS WITH HIGHEST PURCHASE VALUE =====");

        for (int i = 0; i < count; i++) {
            System.out.println(
                    (i + 1) + ". "
                    + customerNames[i]
                    + " - "
                    + totalMoney[i]
                    + " VND");
        }
    }
}